name = "medcheck"
main = "src/index.ts"
compatibility_date = "2025-01-01"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "medcheck-db"
database_id = "9db8edc7-4928-4c25-b441-72db15c08493"

[vars]
ENVIRONMENT = "production"
APP_NAME = "MedCheck"
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_MINUTES = "30"
